<?php
/**
 * @file
 * Base module file for loft_faq
 *
 * @defgroup loft_faq FAQ
 * @{
 */

// autocomplete path for this module
define('LOFT_FAQ_AUTOCOMPLETE', 'loft-faq/autocomplete');

/**
 * @var LOFT_FAQ_GROUP_DEFAULT
 * The default group
 */
define('LOFT_FAQ_GROUP_DEFAULT', 'General');

/**
 * @var LOFT_FAQ_GROUP_FIELDNAME
 *
 * The fieldname that contains the group string.
 */
define('LOFT_FAQ_GROUP_FIELDNAME', 'field_group');
/**
 * @var LOFT_FAQ_SET_DEFAULT
 *
 * Default value for admin setting.
 */
define('LOFT_FAQ_SET_DEFAULT', TRUE);
/**
 * @var LOFT_FAQ_NODE_TYPE
 *
 * The default node type to use as an faq
 */
define('LOFT_FAQ_NODE_TYPE', 'loft_faq');

/**
 * @var LOFT_FAQ_VIEWS_DISPLAY
 *
 * The display that is used to programatically get the faqs.
 */
define('LOFT_FAQ_VIEWS_DISPLAY', 'attachment_1');

/**
 * @var LOFT_FAQ_PATH_ADMIN_SETTINGS
 *
 * Path to admin settings
 */
define('LOFT_FAQ_PATH_ADMIN_SETTINGS', 'admin/structure/loft-faq');

/**
 * Get functional nodes; these should not be deleted!
 *
 * If nid is provided return bool if this is a core node
 *
 * @return array or bool
 */
function _loft_faq_core_nodes($nid = NULL) {
  $core_nids = loft_faq_get_pages_info('ids');
  if ($nid) {
    return in_array($nid, $core_nids);
  }
  return $core_nids;
}

/**
 * Implements hook_form_alter().
 */
function loft_faq_form_alter(&$form, $form_state, $form_id) {
  global $_loft_faq_type_;
  $is_node_form = !empty($form['#node_edit_form']);

  if ($is_node_form) {
    $nid = $form['nid']['#value'];
    
    // Remove the ability to delete the FAQs pages.
    if(_loft_faq_core_nodes($nid)) {
      unset($form['actions']['delete']);
    }

    if ($form['#node']->type === $_loft_faq_type_) {
      module_load_include('inc', 'loft_faq', 'includes/loft_faq.admin');
      _loft_faq_faq_form_alter($form);
    }  
  }
}

/**
 * Implements hook_help().
 *
 * http://api.drupal.org/api/function/hook_help
 *
 * @param string $path
 *   The router menu path, as defined in hook_menu(), for the help that is
 *   being requested; e.g., 'admin/node' or 'user/edit'. If the router path
 *   includes a % wildcard, then this will appear in $path; for example, node
 *   pages would have $path equal to 'node/%' or 'node/%/view'. Your hook
 *   implementation may also be called with special descriptors after a "#" sign.
 * @param array $arg
 *   An array that corresponds to the return value of the arg() function, for
 *   modules that want to provide help that is specific to certain values of
 *   wildcards in $path. For example, you could provide help for the path
 *   'user/1' by looking for the path 'user/%' and $arg[1] == '1'. This array
 *   should always be used rather than directly invoking arg(), because your
 *   hook implementation may be called for other purposes besides building the
 *   current page's help. Note that depending on which module is invoking
 *   hook_help, $arg may contain only empty strings. Regardless, $arg[0] to
 *   $arg[11] will always be set.
 */
function loft_faq_help($path, $arg) {
  $help = '';
  switch ($path) {
    case 'admin/help#loft_faq':
      $help .= check_markup(file_get_contents(drupal_get_path('module', 'loft_faq') . '/README.txt'), 'plain_text');
      return $help;

    case 'node/%/edit':
      if (in_array($arg[1], loft_faq_get_pages_info('ids'))) {
        $help = '<p>' . t('The <strong>Frequently Asked Questions</strong> are appended to the content of this node. <a href="@url">Adjust settings.</a>', array('@url' => url(LOFT_FAQ_PATH_ADMIN_SETTINGS))) . '</p>';
      }
      return $help;
  }
}

/**
 * Implements hook_init().
 */
function loft_faq_init() {

  // Identify the node type for each faq.
  global $_loft_faq_type_, $_loft_faq_display;
  $_loft_faq_type_   = variable_get('loft_faq_node_type', LOFT_FAQ_NODE_TYPE);
  $_loft_faq_display = variable_get('loft_faq_views_display', LOFT_FAQ_VIEWS_DISPLAY);

  if (user_access('administer loft_faq')
    && $_GET['q'] != LOFT_FAQ_PATH_ADMIN_SETTINGS
    && !loft_faq_get_pages_info()) {
    drupal_set_message(t('Please define which node to use as your FAQ page by visiting <a href="@url">@url</a>, or disable the Frequently Asked Questions module.', array('@url' => url(LOFT_FAQ_PATH_ADMIN_SETTINGS))), 'warning', FALSE);
  }
}

/**
 * Implements hook_perm().
 */
function loft_faq_permission() {
  return array(
    'administer loft_faq' => array(
      'title' => t('Administer loft_faq'),
      'description' => t('Perform administration tasks for loft_faq.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function loft_faq_menu() {
  global $_loft_faq_type_;
  $items = array();

  $items[LOFT_FAQ_PATH_ADMIN_SETTINGS] = array(
    'title' => 'FAQ settings',
    'description' => 'Configure how FAQ behaves.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('loft_faq_admin_settings'),
    'file' => 'loft_faq.admin.inc',
    'access arguments' => array('administer loft_faq'),
    'type' => MENU_NORMAL_ITEM,
  );

  foreach (loft_faq_get_pages_info('bundle_types') as $bundle_type) {
    $items[LOFT_FAQ_AUTOCOMPLETE . "/$_loft_faq_type_"] = array(
      'title' => "autocomplete for loft_faq: $_loft_faq_type_ nodes",
      'page callback' => 'loft_faq_autocomplete',
      'page arguments' => array($_loft_faq_type_),
      // All this path does is expose public categories so the access
      // can be always true.
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
      'file' => 'includes/loft_faq.admin.inc',
    );    
  }

  return $items;
}

/**
 * Implementats hook_preprocess_html().
 */
function loft_faq_preprocess_html(&$vars) {
  if (($node = menu_get_object())
    && in_array($node->nid, loft_faq_get_pages_info('ids'))) {
    $vars['classes_array'][] = 'loft-faq-page';
  }
}

/**
 * Determine first and last classes
 *
 * @param string $key
 *   A unique id for this batch
 * @param array
 *   This is the array of all items to monitor
 */
function _loft_faq_get_iteration_classes($key, $array) {
  static $progress = array();
  $classes = array();
  if (empty($progress[$key])) {
    $progress[$key] = 1;
    $classes[] = 'first';
  }
  if (count($array) == $progress[$key]) {
    $classes[] = 'last';
  }
  ++$progress[$key];
  return $classes;
}

/**
 * Implements hook_loft_faq_node_append().
 */
function loft_faq_loft_faq_node_append() {
  return array(
    array(
      'nid' => variable_get('loft_faq_faq_page_nid', NULL),
    )
  );
}

/**
 * Implements hook_library().
 */
function loft_faq_library() {
  return array(
    'loft_faq' => array(
      'title' => 'Loft FAQ',
      'version' => '1.0',
      'js' => array(
        drupal_get_path('module', 'loft_faq') . '/js/jquery.scrolling_anchors.min.js' => array(),
        drupal_get_path('module', 'loft_faq') . '/js/loft_faq.min.js' => array(),
      ),
      'css' => array(
        drupal_get_path('module', 'loft_faq') . '/css/loft_faq.css' => array(
          'type' => 'file',
          'media' => 'screen',
        )
      ),
    )
  );
}



/**
 * Implements hook_theme().
 */
function loft_faq_theme($existing, $type, $theme, $path) {
  return array(
    'loft_faq_toc' => array(
      'variables' => array(
        'items' => array(),
        'total_faqs' => 0,
        'total_fags_by_category' => array(),
      ),
      'file' => 'includes/loft_faq.theme.inc',
      'template' => 'templates/loft_faq-toc',
    ),
    'loft_faq_list' => array(
      'variables' => array(
        'items' => array(),
        'wrapper_attributes' => array(),
        'anchor' => NULL,
        'category' => NULL,
        'has_toc' => TRUE,
        'title_display' => 'before',
      ),
      'file' => 'includes/loft_faq.theme.inc',
      'template' => 'templates/loft_faq-list',
    ),
    'loft_faq_item' => array(
      'variables' => array(
        'total_faqs_by_category' => array(),
        'node' => NULL,
        // If these three are provided they will trump the node.
        'category' => '',
        'question' => '',
        'answer' => '',
      ),
      'file' => 'includes/loft_faq.theme.inc',
      'template' => 'templates/loft_faq-item',
    ),
  );
}

/**
 * Get a list of faq nodes by category
 *
 * They are ordered by weight field
 *
 * @param NULL|string $category
 *
 * @return array
 * - an array of nodes keyed by nid when $category is not null.
 * - when it's null you will get the following:
 *   - #count
 *   - #categories
 *   - #category_counts array of ints
 *   - category1, 2...
 */
function loft_faq_get_faq_by_category($category = NULL, $reset = FALSE) {
  global $_loft_faq_type_, $_loft_faq_display;

  static $drupal_static_fast;
  if (!isset($drupal_static_fast)) {
    $drupal_static_fast['faqs'] = &drupal_static(__FUNCTION__, NULL);
  }
  $faqs = &$drupal_static_fast['faqs'];
  if ($reset || !isset($faqs)) {

    $view_args_base = array(
      // This the view name, not the node type!!!
      'loft_faq',
      $_loft_faq_display,
      $_loft_faq_type_,
    );
    $faqs = array(
      '#count' => 0,
      '#categories' => loft_faq_get_faq_categories($reset),
      '#category_counts' => array(),
    );

    foreach ($faqs['#categories'] as $_category) {
      $faqs['#category_counts'][$_category] = 0;
      $faqs[$_category]                     = array();
      $view_args                            = array_merge($view_args_base, array($_category));
      $result                               = (array) call_user_func_array('views_get_view_result', $view_args);
      foreach ($result as $data) {
        $node          = node_load($data->nid);
        $node_category = loft_faq_get_node_category($node);
        if ($node_category === $_category) {
          $faqs[$_category][$node->nid] = $node;
          $faqs['#category_counts'][$_category]++;
        }
      }
      $faqs['#count'] += count($faqs[$_category]);
    }
  }
  
  if (!isset($category)) {
    return $faqs;
  }
  return isset($faqs[$category]) ? $faqs[$category] : array();
}

/**
 * Get an array of FAQ categories
 *
 * @return array
 *   keys are irrelevant, values are human names
 */
function loft_faq_get_faq_categories($reset = FALSE) {
  global $_loft_faq_type_, $_loft_faq_display;
  static $categories;
  if (empty($categories) || $reset) {
    $result     = (array) views_get_view_result('loft_faq', $_loft_faq_display, $_loft_faq_type_);
    $categories = array();
    $default    = variable_get('loft_faq_group_default', LOFT_FAQ_GROUP_DEFAULT);
    foreach ($result as $data) {
      $node = node_load($data->nid);
      //empty category
      if (!($category = loft_faq_get_node_category($node))) {
        $category = loft_faq_set_node_category($default);
      }
      if (!in_array($category, $categories)) {
        $categories[] = $category;
      }
    }
    asort($categories);

    drupal_alter('loft_faq_categories', $categories);
  }

  return $categories;
}

/**
 * Implements hook_node_load().
 */
function loft_faq_node_load($nodes, $types) {
  global $_loft_faq_type_;
  if (!in_array($_loft_faq_type_, $types)) {
    return;
  }
  $default = variable_get('loft_faq_group_default', LOFT_FAQ_GROUP_DEFAULT);
  foreach ($nodes as $node) {
    if ($default && !loft_faq_get_node_category($node)) {
      loft_faq_set_node_category($node, $default);
    }
  }
}

/**
 * Get the category of a node
 *
 * @param object $node
 *
 * @return string
 */
function loft_faq_get_node_category($node) {
  $group_field = variable_get('loft_faq_group_fieldname', LOFT_FAQ_GROUP_FIELDNAME);
  $category    = empty($node->{$group_field}['und'][0]['value']) ? NULL : trim($node->{$group_field}['und'][0]['value']);
  drupal_alter('loft_faq_get_node_category', $category, $node);
  return $category;
}

/**
 * Set the category of a node
 *
 * @param object $node
 * @param string $category
 *
 * @return string
 */
function loft_faq_set_node_category($node, $category) {
  $group_field = variable_get('loft_faq_group_fieldname', LOFT_FAQ_GROUP_FIELDNAME);
  $node->{$group_field}['und'][0]['value'] = $category;
  if (array_key_exists('safe_value', $node->{$group_field}['und'][0])) {
    $node->{$group_field}['und'][0]['safe_value'] = trim(check_plain($category));
  }
  drupal_alter('loft_faq_set_category', $category, $node);
  return $category;
}

/**
 * Determine if the faq is in a certain category
 *
 * @param object $node
 * @param string $category
 *
 * @return bool
 */
function loft_faq_in_category($node, $category) {
  if ($has = loft_faq_get_node_category($node)) {
    return $category == $has;
  }
  return FALSE;
}

/**
 * Implements hook_sort_views_views().
 *
 * Define any views that you wish to be sortable
 *
 * Each key of the array is a view name that you want to enable sorting on
 *
 * Each element is an array with the following keys:
 * - sort_field: the fieldname that is used by the node type(s) to store the
 *   sorting index, should be a field of type integar textfield
 *
 * @return array()
 */
function loft_faq_sort_views_views() {
  global $_loft_faq_type_;
  return array(
    $_loft_faq_type_ => array(
      'sort_field' => 'field_sort',
    ),
  );
}

/**
 * Gets info about the faq node.
 *
 * @param  string $key One of:
 *   - NULL
 *   - config
 *   - ids
 *   - entities
 *   - entity_types
 *   - bundle_types
 *
 * @return array
 *   When key is ... the return is ...
 *   - NULL ... array(array($entity, $id, $entity_type, $bundle_type))
 *   - config ... keyed by id, array of config options
 *   - ids ... array($id, $id, $id ...)
 *   - entities ... array($entity, $entity, ...)
 *   - entity_types ... array( {{ all entity types}} )
 *   - bundle_types ... array ( {{ all bundle type }} )
 */
function loft_faq_get_pages_info($key = NULL) {
  static $drupal_static_fast;
  if (!isset($drupal_static_fast)) {
    $drupal_static_fast['info'] = &drupal_static(__FUNCTION__, NULL);
  }
  $info = &$drupal_static_fast['info'];
  if (!isset($info)) {
    $info   = array();
    $append = module_invoke_all('loft_faq_node_append');

    // Cycle through to see if this node is there
    $nodes = $bundles = $items = array();
    foreach ($append as $config) {
      $node = $id = $bundle_type = NULL;
      $config += array(
        'nid' => NULL,
        'categories' => array(),
        'title' => '',
        'not_categories' => array(),
      );

      if (($node = node_load($config['nid']))) {
        $info['config'][$node->nid]        = $config;
        $info['nodes'][$node->nid]         = $node;
        $info['bundle_types'][$node->type] = $node->type;
        $info['items'][]                   = array($node, $node->nid, 'node', $node->type, $config);
      }
    }

    // Take care of defaults
    $info += array(
      'nodes' => array(),
      'bundle_types' => array(),
      'config' => array(),
      'items' => array(),
    );
  }

  switch ($key) {
    case 'ids':
      return array_keys($info['nodes']);
    case 'nodes':
      return $info['nodes'];
    case 'entity_types':
      return array('node');
    case 'bundle_types':
      return $info['bundle_types'];
    case 'config':
      return $info['config'];  
    case NULL:
      return $info['items'];
    default:
      throw new \InvalidArgumentException("Invalid key $key.");
  }
  
  return $info;
}

/**
 * Implements hook_field_extra_fields().
 */
function loft_faq_field_extra_fields() {
  $entities = loft_faq_get_pages_info('entity_types');
  $bundles  = loft_faq_get_pages_info('bundle_types');

  foreach ($entities as $entity_type) {
    foreach ($bundles as $bundle_type) {
      $extra[$entity_type][$bundle_type]['display'] = array(
        'loft_faq_extra_field_category_list' => array(
          'label' => t('FAQ: Category List'),
          'weight' => 0,
        ),
        'loft_faq_extra_field_questions' => array(
          'label' => t('FAQ: Questions'),
          'weight' => 0,
        ),
      );
    }
  }

  return $extra;
}


/**
 * Adds a new element to $node->content, $node->content['loft_faq']
 *
 * @param object $node
 * @param string $view_mode
 * @param string $langcode
 */
function loft_faq_build_content($node, $view_mode, $langcode) {
  static $drupal_static_fast;
  if (!isset($drupal_static_fast)) {
    $drupal_static_fast['content'] = &drupal_static(__FUNCTION__, NULL);
  }
  $content   = &$drupal_static_fast['content'];
  
  $hash_args = func_get_args();
  unset($hash_args[0]->content);
  $hash      = md5(json_encode($hash_args));

  if (!isset($content[$hash])) {
    // Cycle through to see if this node is there
    foreach (loft_faq_get_pages_info('config') as $config) {

      // We need to append to this node
      if ($config['nid'] == $node->nid) {

        // Try to load categories...
        if (!($categories = loft_faq_get_faq_categories())

            // Filter categories
            || (array_key_exists('categories', $config)
                && is_array($config['categories'])
                && count($config['categories'])
                && !($categories = array_intersect($config['categories'], $categories)))

            // Remove not_categories
            || (array_key_exists('not_categories', $config)
                && is_array($config['not_categories'])
                && count($config['not_categories'])
                && !($categories = array_diff($categories, $config['not_categories'])))){
          // The filter removed all categories so we're done here
          return;
        };

        $toc = $list = array();


        // We only are going to show title if we have more than one category.
        // as well as the toc.
        $default_title_display = 'hidden';
        $toc_display = FALSE;
        if (count($categories) > 1) {
          $toc_display = TRUE;
          $default_title_display = 'before';
        }
        $config += array(
          'toc' => $toc_display,
          'title_display' => $default_title_display,
        );
        module_load_include('inc', 'loft_faq', 'includes/loft_faq.theme');

        foreach ($categories as $category) {
          $category = empty($category)
            ? variable_get('loft_faq_group_default', LOFT_FAQ_GROUP_DEFAULT)
            : $category;
          $category_safe = check_plain($category);
          $index = 1;
          $anchor = loft_faq_css_safe($category);
          $items = array();
          $faqs_data = loft_faq_get_faq_by_category();
          if (isset($faqs_data[$category]) && ($nodes = $faqs_data[$category])) {
            $toc[$anchor] = $category_safe;
            foreach ($nodes as $faq_node) {
              $item = array(
                '#theme' => 'loft_faq_item',
                '#total_fags_by_category' => $faqs_data['#category_counts'],
                '#category' => $category_safe,
                '#anchor' => $anchor,
                '#node' => $faq_node,
                // '#total_faqs' => $faqs_data['#count'],
                // these are now in loft_faq_preprocess_loft_faq_item
                // '#total_category_faqs' => count($nodes),
                // '#categories' => $faqs_data['#categories'],
              );
              drupal_alter('loft_faq_item', $item);
              $items[] = $item;
            }

            // This is the list of items in this category.
            $category = empty($config['title']) ? $category_safe : $config['title'];
            $list[$category] = array(
              '#theme' => 'loft_faq_list',
              '#total_faqs' => $faqs_data['#count'],
              '#total_category_faqs' => count($items),
              '#total_fags_by_category' => $faqs_data['#category_counts'],
              '#categories' => $faqs_data['#categories'],
              '#category' => $category,
              '#title_display' => $config['title_display'],
              '#has_toc' => $config['toc'],
              '#anchor' => $anchor,
              '#items' => $items,
            );

            $classes = _loft_faq_get_iteration_classes('categories', $categories);
            $classes[] = 'loft-faq-category-wrapper';
            $classes[] = $anchor;
            $list[$category]['#wrapper_attributes']['class'] = $classes;
          }
        }

        $content[$hash]  = array(
          '#type' => 'container',
        );

        // Append the TOC?
        if ($config['toc']) {
          $content[$hash]['toc'] = array(
            '#theme' => 'loft_faq_toc',
            '#total_faqs' => $faqs_data['#count'],
            '#total_fags_by_category' => $faqs_data['#category_counts'],
            '#items' => $toc,
            '#weight' => isset($node->content['body']) ? $node->content['body']['#weight'] + 1 : 0,
          );
        }

        $content[$hash]['list'] = $list;
        $content[$hash]['list']['#attached']['library'][] = array('loft_faq', 'loft_faq');
      }
    }
  }
  $node->content['loft_faq'] = $content[$hash];
}

/**
 * Checks if a view_mode is enabled for a bundle, if not, returns default.
 *
 * This should be used when pulling settings from field_info_extra_fields().
 *
 * @param  string $entity_type
 * @param  string $bundle_type
 * @param  string $view_mode
 *
 * @return string $view_mode|'default'
 *
 * @see field_info_extra_fields()
 * @see hook_field_extra_fields
 */
function _loft_faq_get_real_view_mode($entity_type, $bundle_type, $view_mode) {
  $entity_info = entity_get_info($entity_type, $bundle_type);
  $view_modes  = $entity_info['view modes'];

  return !empty($view_modes[$view_mode]['custom_settings']) ? $view_mode : 'default';
}

/**
 * Implements hook_entity_view().
 */
function loft_faq_entity_view($entity, $type, $view_mode, $langcode) {
  list($entity_id) = entity_extract_ids($type, $entity);

  if (in_array($entity_id, loft_faq_get_pages_info('ids'))) {
    $info              = entity_get_info($type);
    $bundle_type       = empty($info['entity keys']['bundle']) ? NULL : $entity->{$info['entity keys']['bundle']};
    $extra_fields_info = field_info_extra_fields($type, $bundle_type, 'display');
    $view_mode         = _loft_faq_get_real_view_mode($type, $bundle_type, $view_mode);
    
    // Important to clone this here so our hashing in loft_faq_build_content works correctly.
    $node              = clone $entity;
    
    $show_toc = FALSE;
    if (!empty($extra_fields_info['loft_faq_extra_field_category_list']['display'][$view_mode]['visible'])) {
      $show_toc = TRUE;
      loft_faq_build_content($node, $view_mode, $langcode);
      $entity->content['loft_faq_extra_field_category_list'] = $node->content['loft_faq']['toc'];
    }

    if (!empty($extra_fields_info['loft_faq_extra_field_questions']['display'][$view_mode]['visible'])) {
      loft_faq_build_content($node, $view_mode, $langcode);

      // Disable toc if not shown based on extra fields info.
      if (!$show_toc && isset($node->content['loft_faq']['list'])) {
        foreach ($node->content['loft_faq']['list'] as &$category) {
          $category['#has_toc'] = $show_toc;
        }
      }

      $entity->content['loft_faq_extra_field_questions'] = isset($node->content['loft_faq']['list']) ? $node->content['loft_faq']['list'] : array();
    }
  }
}

/**
 * Implements hook_entity_view_alter().
 */
function loft_faq_entity_view_alter(&$build, $entity_type) {
  if ($entity_type === 'node'
    && in_array($build['#node']->nid, loft_faq_get_pages_info('ids'))
    && (user_access('create loft_faq content') || user_access('administer loft_faq'))) {
      
      $info  = loft_faq_get_pages_info('config');
      $info  = $info[$build['#node']->nid];
      $query = drupal_get_destination();
      $query['loft_faq_display'] = $build['#node']->nid;
      $build['links']['loft_faq'] = array(
        '#links' => array(
          array(
            'title' => 'Add another FAQ',
            'href' => 'node/add/loft-faq',
            'query' => $query,
            'attributes' => array('class' => array('loft-faq-add-link')),
          ),
        ),
      );
    }
  }

/**
 * Implements hook_preprocess_views_view().
 */
function loft_faq_preprocess_views_view(&$vars) {
  $view    = &$vars['view'];
  $name    = $vars['name'];
  $display = $vars['display_id'];
  
  if ($name === 'loft_faq' && strpos($display, 'block') === 0) {
    // TODO Create views display plugin?
    $build = array();
    $build = array(
      '#theme' => 'loft_faq_list',
      '#title_display' => 'before',
      '#items' => array(),
      '#has_toc' => FALSE,
    );
    foreach ($view->result as $data) {
      $node = node_load($data->nid);
      $item = array(
        '#theme' => 'loft_faq_item',
        '#total_faqs_by_category' => array(),
        '#node' => $node,
      );
      drupal_alter('loft_faq_item', $item);
      $build['#items'][] = $item;
    }
    module_load_include('inc', 'loft_faq', 'includes/loft_faq.theme');
    $item_vars = _loft_faq_get_category_totals($build['#items']);
    foreach (array_keys($item_vars) as $key) {
      $item_vars['#' . trim($key, '#')] = $item_vars[$key];
      unset($item_vars[$key]);
    }
    foreach ($build['#items'] as &$item) {
      $item += $item_vars;
    }
    $vars['rows'] = render($build);
  }
}
